### ISSUE TITLE
Use truststore without code change

### ISSUE THREAD

**Issue by bendem** [sethmlarson/truststore#127]
I'm deploying scripts and applications which I don't have control of, using system trust should be the default for all those applications.

As a sysadmin, can I somehow force a python script to use truststore without modifying it?

**Comment by davisagli** [comment]
I appreciate this use case and agree it would be nice if there were a simple way to do it. The challenges are replacing the stdlib SSLContext in the correct modules (which is hard to do generally without knowing what libraries you want to target) and making sure that happens early enough (before members of those modules are imported anywhere else).

It might be possible to use the [`sitecustomize`](https://docs.python.org/3/library/site.html#module-sitecustomize) module or some .pth file hack to replace SSLContext in the `ssl` module early during Python startup. We intentionally don't do that in `truststore` itself, since some users would like to use it in a more targeted fashion.

**Comment by sethmlarson** [comment]
@bendem Another option would be to evaluate [pip-system-certs](https://pypi.org/project/pip-system-certs/) package which doesn't have the full set of abilities that Truststore does, but instead loads all system certificates at the time of install into certifi's bundle. This might work for your use-case, but doesn't have the ability to auto-update certificates like Truststore does.
