### ISSUE TITLE
set truststore config file not working

### ISSUE THREAD

**Issue by delassio** [sethmlarson/truststore#133]
Hello,

when settings truststore feature in pip config file:

pip config set global.use-feature truststore

i get error [SSL: CERTIFICATE_VERIFY_FAILED]

thanks

**Comment by sethmlarson** [comment]
Unfortunately we're going to need more information to debug why a certificate verification failure occurred (because verification failure is sometimes the expected outcome!)

Things like:

* Which operating system platform are you using?
* Is this a public URL you're accessing or a private one?
* Is there a proxy (transparent or explicit) involved in your request?
* Is your operating system's trust store configured properly?

Without this information we can't be of much help to figure out the issue, if any.

**Comment by sethmlarson** [comment]
Going to close for now, with more information we can reopen.

**Comment by delassio** [comment]
Hi,


    operating system: Win 10
    public URL
    explicit proxy
    trust store configured properly

Thanks,

when call from cli all is ok > pip --use-feature truststore it works fine
