### ISSUE TITLE
[Question] truststore.SSLContext vs ssl.SSLContext

### ISSUE THREAD

**Issue by khameeteman** [sethmlarson/truststore#154]
Hi,

I am trying to solve a `SSLCertVerificationError` by mounting a custom adapter, similar as you do in your tests here: https://github.com/sethmlarson/truststore/blob/v0.9.2/tests/test_custom_ca.py#L39

I managed to fix this in 2 ways:

1. using your example (simplified for our use case):

```python
class SSLContextAdapter(requests.adapters.HTTPAdapter):
    # simplified version of https://github.com/sethmlarson/truststore/blob/v0.9.2/tests/__init__.py#L5

    def init_poolmanager(self, *args, **kwargs):
        kwargs['ssl_context'] = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        return super().init_poolmanager(*args, **kwargs)
```

2. using the default ssl context:

```python
class SSLContextAdapter(requests.adapters.HTTPAdapter):

    def init_poolmanager(self, *args, **kwargs):
        context = ssl.create_default_context()
        context.load_default_certs()
        kwargs['ssl_context'] = context
        return super().init_poolmanager(*args, **kwargs)
```

And for both methods mounting like below:

```python
session = ...
session.mount("https://", SSLContextAdapter())
```

Could someone explain to me which method is preferred and why? For me option 1 means I need to vendor `truststore` in my library which I try to keep to a minimum.

**Comment by sethmlarson** [comment]
Great question! `load_default_certs()` loads the certificates that are configured by default in OpenSSL (if any) versus Truststore which uses the system certificate APIs for macOS and Windows. For Linux, this means that Truststore and using `load_default_certs()` *should* be the same (assuming that OpenSSL is configured correctly). Truststore also checks some common default paths for system certificates if OpenSSL isn't configured at all but I suspect for most systems this doesn't matter much.

On Windows `load_default_certs` already grabs certificates from the system certificate store, for macOS this isn't the case! So for macOS using Truststore means you're *actually* using system certificates instead of whatever is configured for OpenSSL.

For Windows though, you're using system certificates but the certificates are "point-in-time", so whatever is *already* in the system certificate is what's used. When you use the system certificate APIs on both Windows and macOS the system is able to securely fetch updates to the certificate store either for revocation, missing intermediates, or if there are new root certificates. This is especially important for fresh systems which might be behind on security updates!

Hope this answers your question :)
