### ISSUE TITLE
CRYPT_E_NO_REVOCATION_CHECK when checking a self-signed certificate created by mkcert on Windows 

### ISSUE THREAD

**Issue by uranusjr** [sethmlarson/truststore#42]
After generating a certificate with `mkcert` (using the [example in README](https://github.com/FiloSottile/mkcert)) and starting a server on localhost, `https://localhost` correctly runs in the browser, but using `socket` with `truststore` fails with the following:

```pycon
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> import ssl
>>> import truststore
>>> sock = socket.create_connection(("127.0.0.1", 443))
>>> ctx = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
>>> sock = ctx.wrap_socket(sock, server_hostname="127.0.0.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages\truststore\_api.py", line 54, in wrap_socket
    _verify_peercerts(ssl_sock, server_hostname=server_hostname)
  File "site-packages\truststore\_api.py", line 106, in _verify_peercerts
    _verify_peercerts_impl(
  File "site-packages\truststore\_windows.py", line 318, in _verify_peercerts_impl
    _get_and_verify_cert_chain(
  File "site-packages\truststore\_windows.py", line 410, in _get_and_verify_cert_chain
    raise err from None
ssl.SSLCertVerificationError: ('Certificate chain policy error 0x80092012 [0]',)
```

**Comment by sethmlarson** [comment]
This might be due to how we [configure the call](https://github.com/sethmlarson/truststore/blob/main/src/truststore/_windows.py#L325) to `CertVerifyCertificateChainPolicy` with `CERT_CHAIN_REVOCATION_CHECK_CHAIN`.

**Comment by davisagli** [comment]
@uranusjr The problem here is that truststore is currently asking Windows to check certificate revocation for all certs (like Seth said), but mkcert is not adding a certificate revocation list (CRL) for the CA it created.

In #43 I'm making a change so that we'll conditionally tell Windows whether to check cert revocation based on the SSLContext's `verify_flags`. So you can choose whether to do it by setting [VERIFY_CRL_CHECK_LEAF](https://docs.python.org/3/library/ssl.html#ssl.VERIFY_CRL_CHECK_LEAF) or [VERIFY_CRL_CHECK_CHAIN](https://docs.python.org/3/library/ssl.html#ssl.VERIFY_CRL_CHECK_CHAIN), or you can leave it unset.

**Comment by uranusjr** [comment]
Sounds like a good idea. Which approach do you think should be the default? I’m asking because we need to choose one for pip, and I’m not sure it’s a good idea to add a CLI flag for this. (Or is it?) We can always expose the toggle via environment variable, but it won’t be very discoverable, so a good default is important.

**Comment by davisagli** [comment]
@uranusjr That's a good question, and a hard one to answer. My gut feeling is to enable it (security by default). But that clearly makes it harder to successfully use a custom/internal CA certificate, as you saw here, and I don't have any sense of what proportion of corporate CAs provide a working revocation mechanism in practice.

One option would be for truststore to enable cert revocation checks but ignore errors that have to do with the revocation being unavailable/unreachable. So we would still have a hard failure if the cert can clearly be determined to be revoked, but not if the check is inconclusive. There'd be a possibility of incorrectly accepting a revoked cert if something is blocking network access to where revocation is checked. This appears to be what macOS and chromium do in many cases -- but they also both support additional mechanisms for checking revocation that can help fill the gap. Unfortunately there isn't a way to explicitly request this approach in SSLContext.verify_flags that's distinct from requesting a hard requirement for checking CRLs.

Let me look again at whether there's a way we can distinguish between errors because the CA didn't specify any way to check revocation, and errors because it did but the endpoint can't be reached. Ignoring the former seems lower risk than ignoring the latter.

**Comment by sethmlarson** [comment]
Chatted with @davisagli on this issue, we're going to go ahead with explicitly disabled CRL checks (in line with the default value provided by `ssl.SSLContext.verify_flags`) until we're more confident about a default value that won't fail in the case of custom CA certificates without CRL information.

What this means for pip: the default usage of the `truststore.SSLContext` object won't break on the issue described here so can go ahead as-is.

**Comment by sethmlarson** [comment]
I think we can close this via https://github.com/sethmlarson/truststore/pull/43.
