### ISSUE TITLE
Verify with additional certificates in addition to system certificates

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/truststore#9]
Allow passing additional certificates via `SSLContext.load_verify_locations()`. Only load system certificates when `SSLContext.load_default_certs()` is used.

**Comment by davisagli** [comment]
On Windows, by default CertVerifyCertificateChainPolicy uses a default "chain engine" which only trusts root certs from system cert stores (https://docs.microsoft.com/en-us/windows/win32/seccrypto/certificate-chains has a bit more info on this). So far I think I've found 2 ways we could also trust additional roots loaded with load_verify_locations:

1. After constructing a cert chain with CertGetCertificateChain, check whether the chain's root cert matches any of the certs that have been loaded with load_verify_locations. If so, include CERT_CHAIN_POLICY_ALLOW_UNKNOWN_CA_FLAG in the dwFlags of the CERT_POLICY_PARA structure passed to CertVerifyCertificateChainPolicy so that it won't complain about the root cert that is not trusted by Windows. I believe this approach is also used by oscrypto

2. It looks like it's possible to use CertCreateCertificateChainEngine to create a custom chain engine with a CERT_CHAIN_ENGINE_CONFIG that uses hExclusiveRoot to only trust CA certs from a store we give it. But it doesn't look like it's possible to create one that will trust _both_ the hExclusiveRoot store and the default system stores (though I could certainly be overlooking something). So we might need to call CertCreateCertificateChain and CertVerifyCertificateChainPolicy twice, once with the default chain engine and once with a custom one, and consider the server certs verified as long as they didn't both fail.

**Comment by sethmlarson** [comment]
@davisagli I started a thread on Twitter about potential solutions and received lots of great discussion: https://twitter.com/sethmlarson/status/1510630808524103689

Basically confirms that there is no "easy" way to accomplish this, the typical flow is either custom trust anchors or system ones.

**Comment by davisagli** [comment]
In Go if additional trusted roots have been configured (`opts.Roots` in the diff I'm about to link), then it first tries to verify using the system APIs (i.e. without considering the additional roots), then if that fails it tries to verify using Go's own verifier which takes the additional trusted roots into consideration. https://github.com/golang/go/commit/3544082f75fd3d2df7af237ed9aef3ddd499ab9c

We could do something similar by first attempting the platform-specific verification code, then falling back to OpenSSL if load_verify_locations has been called.

**Comment by sethmlarson** [comment]
@davisagli That seems like a great way to proceed, especially for now :)

**Comment by davisagli** [comment]
> However, is there a way to do a certificate verification in Python without a handshake? We might need a binary extension to do it this way?

I think you're right that there is not (seems to be built in to how the OpenSSL APIs are structured). So for now I drafted a solution using the 2nd approach I listed above (fallback to custom chain engine) in #36
